name: WDX
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
      - attrs
      - minknow-api==5.7.2
      - pod5
      - vbz-h5py-plugin
  - dtaidistance
  - scikit-learn=1.3.1
  - scipy
  - cython=0.29.36
  - toml
  - tqdm
  - numpy=1.24.4
  - pandas
  - joblib
