[sig_norm]
winsor_window = 5
outlier_thresh = 5.0

[sig_extract]
padding = 100
normalization = "none"

[segmentation]
min_obs_per_base = 15
running_stat_width = 30
num_events = 110
normalization = "mean"
barcode_num_events = 25
accept_less_cpts = false
